[features]
seeds = false
skip-lint = false

[programs.devnet]
digital_contract = "4bmYTgHAoYfBBwoELVqUzc9n8DTfFvtt7CodYq78wzir"

[programs.localnet]
digital_contract = "4bmYTgHAoYfBBwoELVqUzc9n8DTfFvtt7CodYq78wzir"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/bhupek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
